### ISSUE TITLE
The normal CSS file has some weird "first" lines

### ISSUE THREAD

**Issue by Adzetko** [metakirby5/yorha#4]
So I'm doing a small project with the compiled CSS you've made from the Stylus project, and I just saw from begenning to line 97, everything is, like, "cloned" in lines from 115 to 211. So I guess it is the CSS generation by Stylus which caused this, but it's quite odd and I wanted to inform you about this issue, since it gave visibility problems, and also some confusing inspection result.

**Comment by metakirby5** [comment]
Thanks for pointing this out - I think it's an issue with how I imported my Stylus files. I'll look into it shortly :)
