### ISSUE TITLE
Remove display: box

### ISSUE THREAD

**Issue by Strum355** [metakirby5/yorha#7]
When running `node-sass-chokadir`, the following warning is given
```
(Emitted value instead of an instance of Error) autoprefixer: /home/noah/TypeScript/2bot-website/client/node_modules/yorha/dist/yorha.css:217:3: You should write display: flex by final spec instead of display: box
```
browsers that only support `display: box`  make up only ~0.41% of all users, so I think it should be fairly safe to remove it so there are no more warnings

**Comment by metakirby5** [comment]
If I recall correctly, this is generated by [Nib](https://github.com/stylus/nib). If you'd like to remove it, consider converting the Stylus to SASS and running it through your own build pipeline for greater control over the output. For the time being, I'm leaving it as-is.
